#!/bin/bash

# your custom configuration


# set terminal app configuration
export TERMINAL_APP_LOG_ENABLED=0

export TERMINAL_APP_PATH='scripts'
export TERMINAL_APP_LOG_PATH='logs'
export TERMINAL_APP_LIB_PATH="$TERMINAL_APP_PATH/lib"
export TERMINAL_APP_TEST_PATH="$TERMINAL_APP_PATH/test"
export TERMINAL_APP_COMMAND_PATH="$TERMINAL_APP_PATH/commands"

# load lib scripts
for lib_file in $TERMINAL_APP_LIB_PATH/*
do
  source $lib_file
done
