#!/bin/bash

#lib-info: helps dispatching commands in scripts/commands/*

source "$TERMINAL_APP_LIB_PATH/color"

function command_print_info {
  __command_path=$1
  __command_name=$( basename $1 )
  __command_info=$( cat "$__command_path" | grep 'command-info:' )

  __command_info_raw=${__command_info:15:60}

  if [ "$__command_info_raw" != "private" ] ;
  then
    space='                     '
    printf "$orange %s %s $__command_info_raw$color_reset\n" "$__command_name" "${space:${#__command_name}}"
  fi
}

function command_print_help {
  __command_path=$1
  __command_name=$( basename $1 )
  __command_info=$( cat "$__command_path" | grep 'command-info:' )
  __command_help=$( cat "$__command_path" | grep 'command-help:' )

  green "${__command_info:15:60}"
  newline
  while read -r line; do
      orange "${line:15:60}"
  done <<< "$__command_help"
}

function command_exec {
  __command_name=$1
  __command_path="$TERMINAL_APP_COMMAND_PATH/$__command_name"

  # if command doesnt exist: print usage
  if [ ! -f $__command_path ]; then
      red "command not found: $__command_path"
      command_exec 'help'
      exit 1
  fi

  # if second arg is help
  if [ "$2" == "help" ] ; then
      command_print_help $__command_path
  fi

  newline
  log_info "running command: $@"

  $__command_path ${@:2}
}
