#!/bin/bash

#lib-info: helps handling mysql databses

source "$TERMINAL_APP_LIB_PATH/color"

function ssh_upload {
  __from=$1
  __to=$2

  ssh_mkdir $(dirname $__to)

  scp -Cr $__from $SSH_SERVER_LOGIN:$__to
}

function ssh_mkdir {
  ssh $SSH_SERVER_LOGIN "mkdir -p $1"
}

function ssh_download {
  __from=$1
  __to=$2

  mkdir -p $(dirname $__to)

  scp -Cr $SSH_SERVER_LOGIN:$__from $__to
}

function ssh_run {
  ssh $SSH_SERVER_LOGIN $@
}
